package runner

import (
	"strings"
	"encoding/json"
	"os"
	"fmt"
	"path/filepath"
	"time"
  "gopkg.in/yaml.v3"

	"github.com/urfave/cli/v2"
	"github.com/Noswad123/ideomancer/internal/helper"
	"github.com/Noswad123/ideomancer/internal/common"
)
func RunCreateManifestCommand(c *cli.Context) error {
	name := c.String("name")
	id := c.String("id")
	out := c.String("out")
	if strings.TrimSpace(name) == "" {
		fmt.Fprintln(os.Stderr, "error: --name is required")
		os.Exit(2)
	}
	mID := id
	if strings.TrimSpace(mID) == "" {
		mID = helper.Kebab(name)
	}

	// Skeleton manifest aligned with your spec
	m := common.Manifest{
		SchemaVersion: "0.2.0",
		ID:            mID,
		Name:          name,
		Version:       "0.1.0",
		Summary:       "Ideomancer manifest",
		Lore: &common.Lore{
			Aliases:     []string{},
			Epithet:     "Shaper of Intent",
			Description: "Generated by ideomancer manifest:init on " + time.Now().Format(time.RFC3339),
		},
		Resources: []common.Resource{
			{
				Name:        "Manifest",
				Kind:        "consumable",
				DefaultMime: "application/vnd.map.manifest+json",
				MimeTypes:   []string{"application/vnd.map.manifest+json", "application/json"},
				SchemaRef:   "./schemas/manifest.schema.json",
				Description: "A document that defines a system at a high level",
			},
			{
				Name:        "SystemMap",
				Kind:        "consumable",
				DefaultMime: "application/vnd.map.graph+json",
				MimeTypes:   []string{"application/vnd.map.graph+json", "text/mermaid", "text/vnd.graphviz-dot"},
				SchemaRef:   "./schemas/system-map.schema.json",
			},
			{
				Name:      "Watcher",
				Kind:      "process",
				SchemaRef: "./schemas/watcher.schema.json",
			},
		},
		Ops: []common.Op{
			{Name: "manifest.create", Produces: []common.OpRef{{Resource: "Manifest"}}},
			{Name: "manifest.validate", Consumes: []common.OpRef{{Resource: "Manifest"}}, Produces: []common.OpRef{{Resource: "Manifest"}}},
			{Name: "systemMap.generate", Consumes: []common.OpRef{{Resource: "Manifest"}}, Produces: []common.OpRef{{Resource: "SystemMap"}}},
			{Name: "watcher.start", Produces: []common.OpRef{{Resource: "Watcher"}}},
		},
		Events: []common.Event{
			{Name: "map.generated", PayloadRef: "./schemas/events/map-generated.json"},
		},
		Interfaces: common.Interfaces{
			CLI: &common.CLI{
				Commands: []common.CLICommand{
					{Name: "manifest:init", Op: "manifest.create", Args: []common.CLIArg{
						{Name: "id", Type: "string", Required: false},
						{Name: "name", Type: "string", Required: true},
					}},
					{Name: "manifest:validate", Op: "manifest.validate"},
					{Name: "generate:map", Op: "systemMap.generate", Args: []common.CLIArg{
						{Name: "format", Type: "string", Required: false},
					}},
					{Name: "watcher:run", Op: "watcher.start"},
				},
			},
		},
	}

	// If --out is provided, enforce extension and non-existence
	if strings.TrimSpace(out) != "" {
		extOK := strings.HasSuffix(out, ".idman.json") || strings.HasSuffix(out, ".idman.yaml")
		if !extOK {
			fmt.Fprintln(os.Stderr, "error: --out must end with .idman.json or .idman.yaml")
			os.Exit(2)
		}
		if helper.Exists(out) {
			fmt.Fprintf(os.Stderr, "error: file already exists: %s\n", out)
			os.Exit(2)
		}

		dir := filepath.Dir(out)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			helper.FailIO(err)
			return nil
		}

		var bytes []byte
		var err error
		if strings.HasSuffix(out, ".idman.yaml") {
			bytes, err = yaml.Marshal(m)
		} else {
			bytes, err = json.MarshalIndent(m, "", "  ")
		}
		if err != nil {
			helper.FailIO(err)
			return nil
		}
		if err := os.WriteFile(out, bytes, 0o644); err != nil {
			helper.FailIO(err)
			return nil
		}
		fmt.Fprintf(os.Stderr, "wrote %s\n", out)
		return nil
	}

	// No --out → print JSON to stdout
	enc := json.NewEncoder(os.Stdout)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(m); err != nil {
		helper.FailIO(err)
	}

	return nil
}


